#### Consider the below code to answer further questions:

In [1]:
import numpy as np
list_ = [ "1", "2", "3", "4", "5" ]
array_list = np.array(object = list_)
print(array_list)

['1' '2' '3' '4' '5']


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
import numpy as np

# Define the list
list_ = ['1', '2', '3', '4', '5']
# Create a NumPy array from the list
array_list = np.array(object=list_)

# Print the data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [3]:
# Print the data type of each element in the list
print("\nData types of elements in list_:")
for item in list_:
    print(f"Element: {item}, Type: {type(item)}")

# Print the data type of each element in the NumPy array
print("\nData types of elements in array_list:")
for item in array_list:
    print(f"Element: {item}, Type: {type(item)}")


Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.str_'>
Element: 2, Type: <class 'numpy.str_'>
Element: 3, Type: <class 'numpy.str_'>
Element: 4, Type: <class 'numpy.str_'>
Element: 5, Type: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [4]:
import numpy as np

# Define the original list
list_ = ['1', '2', '3', '4', '5']

# Create a NumPy array from the list with dtype=int
array_list = np.array(object=list_, dtype=int)

# Print the data types of the original list elements
print("Data types of elements in list_:")
for item in list_:
    print(f"Element: {item}, Type: {type(item)}")

# Print the data types of the elements in the modified NumPy array
print("\nData types of elements in array_list:")
for item in array_list:
    print(f"Element: {item}, Type: {type(item)}")

Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.int32'>
Element: 2, Type: <class 'numpy.int32'>
Element: 3, Type: <class 'numpy.int32'>
Element: 4, Type: <class 'numpy.int32'>
Element: 5, Type: <class 'numpy.int32'>


In [5]:
import numpy as np

# Given list
num_list = [[1, 2, 3], [4, 5, 6]]

# Creating a NumPy array from the list
num_array = np.array(object=num_list)

# (i) Finding the shape of the array
array_shape = num_array.shape

# (ii) Finding the size of the array
array_size = num_array.size

# Printing the results
print("Shape of num_array:", array_shape)
print("Size of num_array:", array_size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [6]:
import numpy as np

# Creating a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

# Printing the resulting array
print("3x3 Matrix of Zeros:")
print(zero_matrix)

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

# Alternatively, you can use:
# identity_matrix = np.identity(5)

# Printing the resulting identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
